### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'A'

### ISSUE THREAD

**Issue by gopikrishnangs44** [MBlaschek/igra#1]
ValueError: invalid literal for int() with base 10: 'A'

Code:

data, station = igra.read.igra("INM00042369", "temp_12z-mly.txt.zip") 

Please help in this error

**Comment by MBlaschek** [comment]
Hello,

I just tried what you did and it works for me. So it must be something specific you do!?

Tested using Python 3.8.5, Anaconda3, xarray 2022.3.0, pandas 1.1.3, numpy 1.23.5

Maybe try to download the file again:

```py
# import the package
import igra
# download the data
igra.download.station("INM00042369", "/tmp")
# read the data
data, station = igra.read.igra("INM00042369", '/tmp/INM00042369-data.txt.zip')
```

Worked for me.
sorry for the late reply.
